### ISSUE TITLE
Filters not respected for related collections

### ISSUE THREAD

**Issue by KonstantinSchubert** [edelvalle/carbon14#5]
In a query like this:

```
some_collection{
     another_collection(someting:["test"]) {
       message
   }
}
```
, the `something:["test"]` filter is not passed to the `_resolve` method of `another_collection`.

Or so it seems.

**Comment by KonstantinSchubert** [comment]
Alright, so reading the tests, it seems that queries for related objects are expected to be resolved in the `@field` method when the related object is referenced, not in the `_resolve` method of the related object:

```
class Books(Collection):

    id = Field()
    title = Field()
    author = Field(ref='authors')

    _source = BOOKS

    def _resolve(self, level, instances, ctx, ids=All, **kwargs):
        return [i for i in instances if i.id in ids]


class Authors(Collection):

    id = Field()
    name = Field()
    is_alive = Field()
    books = Field(ref='books', many=True)

    _source = AUTHORS

    @field(ref='books', many=True)
    def books(instance, children, title_contains='', *args, **kwargs):
        ids = []
        for book_id in instance.books:
            for book in BOOKS:
                if book.id == book_id and title_contains in book.title:
                    ids.append(book_id)
        return ids

    def _resolve(self, level, instances, ctx, ids=All, **kwargs):
        return [i for i in instances if i.id in ids]
```

I would rather have expected that things work like this:
```

```
class Books(Collection):

    id = Field()
    title = Field()
    author = Field(ref='authors')

    _source = BOOKS

    def _resolve(self, level, instances, ctx, title_contains='', ids=All, **kwargs):
        return [i for i in instances if i.id in ids if title_contains in book.title]


class Authors(Collection):

    id = Field()
    name = Field()
    is_alive = Field()
    books = Field(ref='books', many=True)

    _source = AUTHORS

    @field(ref='books', many=True)
    def books(instance, children, *args, **kwargs):
        ids = []
        for book_id in instance.books:
            for book in BOOKS:
                if book.id == book_id:
                    ids.append(book_id)
        return ids

    def _resolve(self, level, instances, ctx, ids=All, **kwargs):
        return [i for i in instances if i.id in ids]
```
Letting the parameters of the sub-query be handled by the sub-queries `_resolve` method seems more generic to me.

**Comment by KonstantinSchubert** [comment]
After some discussion with @edelvalle, it seems that this issue is very closely tied to a core design choice of carbon14: It first collects all foreign keys pointing to objects of a collection, no matter where and how often the collection is mentioned in the query, and then queries each collection exactly once. Having parameters respected in the way that I expected it would mean that the `_resolve` method would have to be evaluated separately each time the collection is mentioned in the query. Or some other work-around would have to be found.

**Comment by edelvalle** [comment]
https://github.com/edelvalle/carbon14/releases/tag/1.0.0rc
