### ISSUE TITLE
Not all requested properties returned when collection is referenced multiple times.

### ISSUE THREAD

**Issue by KonstantinSchubert** [edelvalle/carbon14#6]
Imagine the following query:
```
some_object {
    object_1_id {
         user_id {
             user_name
         }
    }
    object_2_id {
        user_id{
            user_name
            user_age
        }
    }
}
```
The bug is that `user_age` will not be returned in the query response. Apparently the properties that are queried from a collection are determined by the properties that are mentioned when the collection appears for the first time in a query.

This is very likely linked to carbon14s design of querying each collection only once, instead of querying every time that the collection is mentioned. 

A possible fix might be to always return the union of all properties that are mentioned for a collection in different parts of the query.

**Comment by edelvalle** [comment]
Fixed by https://github.com/edelvalle/carbon14/releases/tag/1.0.0rc
